### ISSUE TITLE
Замечания по коду.

### ISSUE THREAD

**Issue by RadmirT** [mt89vein/c-sharp-console.app#1]
1. Задание выполнено не полностью  согласно заданию должно быть несколько потоков подсчета хеш-сумм
2. Свойства SavedCount,HashedCount, AllFilesCount не являются потокобезопасными
3. Необоснованное определение глобальной  переменой IsExistPath
4. Для передачи значений между методами SelectPath() и Walker() используется глобальная переменная.
5. Необоснованное использование DI
6. Метод Insert(KeyValuePair<string, string> file) класса FileService нигде не используется
7. Присваивание свойства CreatedAt  класса FileEntity в коде нарушает принцип разграничения ответственности.
8. свойство Id  класса BaseEntity  имеет открытий сеттер, что позволяет его свободно изменять при этом это-же свойство используется в GetHashCode.
9. У BaseEntity необоснованно перегружены операторы  == и !=
10. У класса BaseEntity  непонятно назначение метода GetUnproxiedType
11. Класс не обрабатывает ошибки БД. Они как минимум должны быть выведены к консоль,
12. Складывается впечатление что код "надерган" из разных источников. Часть комментариев на английском часть на русском.
13. Класс Configuration нигде не используется

**Comment by mt89vein** [comment]
1. Не было явно указано что потоков для вычисления хэш сумм должно быть больше 1 ой.
2. Эти свойства действительно не потокобезопасны, но их редактирование производится только внутри использующего его потока и ошибок не возникает.
3, 4. IsExistPath -> изначально планировалось сделать отдельные классы для Walker, Hasher и Writer. И уже реализовав Walker я передумал и скопировал их в Program, таким образом часть вещей я упустил и оставил.
5. Проект должен иметь возможности расширения всегда, имхо. DI удобная вещь, почему бы не использовать её. Ведь вообще можно было просто edmx создать и всё в одном месте без разделения ответственности  и сервисов/моделей =)
6. Опять же забыл удалить при изменении логики.
7.  Я решил что лучше сделаю так, чем буду сперва формировать список, потом его передам в сервис, потом опять по нему проходиться и проставлять дату создания.
8. Это базовый класс, я думаю не стоит запрещать такую возможность.
9, 10. Из старого проекта осталось, не стал трогать.
11. Нет в ТЗ такого чтобы выводить в консоль ошибки с бд. Все ошибки пишутся через LogService и по крайне мере когда я тестировал всё писалось )
12. Код классов BaseEntity и прочее из DAL взят со старого проекта. Там сперва всё писали на англ, потом решили не заморачиваться и поэтому и так и сяк.
13. Он необходим для миграций.

P.s. опыт программирования с потоками на c# нулевой и ограничения (без использования TPL, Concurrent-коллекций) вынуждают делать не совсем хорошие вещи :)

**Comment by RadmirT** [comment]
1. Смотрите внимательно задания: "Рабочие потоки извлекают из очереди описания файлов и выполняют для их содержимого расчет хэш-суммы." Рабочие потоки во множественном лице.
2. Использование глобальных переменных очень плохой подход. Если они используются только одним потоком то они должны быть локальными, если они глобальные, то они должны быть потокобезопасны. 
4. Использование глобальных переменных для передачи значений между потоками очень плохо характеризует программиста, это ошибки "новичков". Ели вы себя позиционируете как подготовленного программиста, то не должны допускать столь детских ошибок. 
5. Если планируется расширение  проекта, то расширение должно поддерживаться на всех слоях приложения, а не только на избранных слоях. Приложение которое в дальнейшем планируется расширять  в первую очередь должно быть покрыть тестами.
7. Очень плохое решение.
8. Очень плохое решение. Это чревато очень серьезными ошибками которые очень сложно поймать. А если это реализовано в базовом классе, это в тройне опасно.
9. Код нужно всегда проверять. И ответы "это из старого проекта/кода" не допустимы.  Тем более для перегрузки операций  == и != нужны очень серьезные основания.
